'use client';
import Link from 'next/link';
import {useState} from 'react';
import {atlas,date,type Ruler,median} from '@/lib/atlas/types';
export function Timeline({rows=atlas.rulers,large=false}:{rows?:Ruler[],large?:boolean}){
 const [zoom,setZoom]=useState(1);const [focus,setFocus]=useState<Ruler|null>(null);
 const groups=atlas.realms.filter(g=>rows.some(r=>r.office_id===g.realm_id));
 const min=32,max=6582,W=1100,left=145,right=35,scale=(v:number)=>left+(v-min)/(max-min)*(W-left-right);
 return <div className="timeline-wrap">{large&&<div className="chart-tools"><span>Horizontal scroll to pan • select a reign for details</span><button onClick={()=>setZoom(Math.max(1,zoom-1))} aria-label="Zoom out">−</button><span>{zoom}×</span><button onClick={()=>setZoom(Math.min(5,zoom+1))} aria-label="Zoom in">+</button><button onClick={()=>setZoom(1)}>Reset</button></div>}<div className="timeline-scroll"><svg viewBox={`0 0 ${W} ${groups.length*53+88}`} style={{width:`${zoom*100}%`,minWidth:720}} role="img" aria-label="Political timeline showing recorded tenures from SA 32 through FA 120">
 <rect x={scale(3441)} y={0} width={scale(6462)-scale(3441)} height={groups.length*53+43} fill="#f1f1ed"/>
 {[32,1000,2000,3000,3442,4441,5441,6441].map((v,i)=><g key={v}><line x1={scale(v)} x2={scale(v)} y1={31} y2={groups.length*53+41} stroke="#deded6" strokeDasharray={v===3442?'0':'2 5'}/><text x={scale(v)} y={groups.length*53+68} textAnchor="middle" className="axis">{i===0?'SA 32':v>3441?`TA ${v-3441}`:`SA ${v}`}</text></g>)}
 <text x={left} y={17} className="era">SECOND AGE</text><text x={scale(3441)+15} y={17} className="era">THIRD AGE</text><text x={W-10} y={17} textAnchor="end" className="era">FA</text>
 {groups.map((g,i)=><g key={g.realm_id}><text x={0} y={61+i*53} className="row-label">{g.name}</text><line x1={left} x2={W-right} y1={56+i*53} y2={56+i*53} stroke="#e5e3da"/>{rows.filter(r=>r.office_id===g.realm_id).map(r=><a key={r.reign_id} href={`/rulers/${r.slug}`} onMouseEnter={()=>setFocus(r)} onFocus={()=>setFocus(r)}><rect x={scale(r.start_sort)} y={42+i*53+(r.status==='overlord'?19:0)} width={Math.max(2,scale(r.end_sort)-scale(r.start_sort)-1)} height={r.status==='overlord'?4:26} fill={g.color} opacity={r.status==='uncertain'?0.5:0.9} rx={1}><title>{`${r.ruler_name}: ${date(r.start_age,r.start_year)} – ${date(r.end_age,r.end_year)} · ${r.reign_years} years · ${r.status}`}</title></rect></a>)}</g>)}
 </svg></div><div className="chart-caption">{focus?<><b>{focus.ruler_name}</b><span>{date(focus.start_age,focus.start_year)} — {date(focus.end_age,focus.end_year)} · {focus.reign_years} years</span><Link href={`/rulers/${focus.slug}`}>View record ↗</Link></>:<><span>Each segment represents one tenure. Overlapping offices are preserved.</span><span>SA = Second Age · TA = Third Age · FA = Fourth Age</span></>}</div></div>
}
export function Distribution({rows=atlas.rulers}:{rows?:Ruler[]}){
 const groups=atlas.realms.filter(g=>rows.some(r=>r.office_id===g.realm_id&&r.eligible));const x=(v:number)=>155+v/420*600;
 return <div className="svg-scroll"><svg viewBox={`0 0 800 ${groups.length*48+50}`} role="img" aria-label="Individual reign lengths and median by institution" style={{minWidth:530}}>{[0,100,200,300,400].map(v=><g key={v}><line x1={x(v)} x2={x(v)} y1={0} y2={groups.length*48} stroke="#e1e2dc"/><text x={x(v)} y={groups.length*48+25} className="axis" textAnchor="middle">{v} yr</text></g>)}{groups.map((g,i)=>{const rs=rows.filter(r=>r.office_id===g.realm_id&&r.eligible);const m=median(rs.map(r=>r.reign_years));return <g key={g.realm_id}><text x={0} y={i*48+26} className="row-label">{g.name}</text>{rs.map((r,j)=><a key={r.reign_id} href={`/rulers/${r.slug}`}><circle cx={x(r.reign_years)} cy={i*48+22+(j%3-1)*6} r={4} fill={g.color} opacity={.65}><title>{`${r.ruler_name} · ${r.reign_years} years`}</title></circle></a>)}<line x1={x(m)} x2={x(m)} y1={i*48+7} y2={i*48+37} stroke="#252b28" strokeWidth={2}/></g>})}</svg></div>
}
export function Longevity(){const rs=atlas.rulers.filter(r=>r.office_id==='numenor'&&r.lifespan!==null&&r.birth_year!==null&&r.birth_age==='SA'&&r.eligible);return <div className="svg-scroll"><svg viewBox="0 0 650 250" role="img" aria-label="Recorded lifespan against birth year of eligible Númenórean rulers">{[200,300,400].map(v=><g key={v}><line x1={40} x2={630} y1={220-(v-150)/300*200} y2={220-(v-150)/300*200} stroke="#deded6"/><text x={0} y={224-(v-150)/300*200} className="axis">{v}</text></g>)}{[0,1000,2000,3000].map(v=><text key={v} x={40+v/3200*590} y={246} className="axis" textAnchor="middle">SA {v||1}</text>)}{rs.map(r=><a href={`/rulers/${r.slug}`} key={r.reign_id}><circle cx={40+(r.birth_year??0)/3200*590} cy={220-((r.lifespan??0)-150)/300*200} r={5} fill="#a27c38" stroke="#fcfbf6" strokeWidth={2}><title>{`${r.ruler_name} · ${r.lifespan} years`}</title></circle></a>)}</svg></div>}
